// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AccessTokenOutputDto = {
    AccessToken?: string | null;
    RefreshNonce?: string | null;
};

export type AcknowlegdementDto = {
    Acknowledgements: string | null;
};

export type ActiveTransfer = {
    BackendAction?: string | null;
    BackendPath?: string | null;
    BackendFileSize?: number;
    BackendFileProgress?: number;
    BackendSpeed?: number;
    BackendIsBlocking?: boolean;
};

export type ArgumentType = 'String' | 'Integer' | 'Boolean' | 'Timespan' | 'DateTime' | 'Size' | 'Enumeration' | 'Path' | 'Password' | 'Flags' | 'Decimal' | 'Unknown';

export type BackupAndScheduleInputDto = {
    Backup: BackupInputDto;
    Schedule?: ScheduleInputDto;
};

export type BackupAndScheduleOutputDto = {
    Backup: BackupDto;
    Schedule: ScheduleDto;
};

export type BackupDto = {
    ID: string | null;
    ExternalID: string | null;
    Name: string | null;
    Description: string | null;
    Tags: Array<string> | null;
    TargetURL: string | null;
    ConnectionStringID?: number;
    OperationType?: OperationType;
    DBPath: string | null;
    DBPathExists: boolean;
    Sources: Array<string> | null;
    Settings: Array<SettingDto> | null;
    Filters: Array<FilterDto> | null;
    Metadata: {
        [key: string]: string;
    } | null;
    IsTemporary: boolean;
    IsUnencryptedOrPassphraseStored: boolean;
    AdditionalTargetURLs: Array<TargetUrlDto> | null;
};

export type BackupInputDto = {
    Name?: string | null;
    Description?: string | null;
    DBPath?: string | null;
    Tags?: Array<string> | null;
    TargetURL?: string | null;
    ConnectionStringID?: number;
    OperationType?: OperationType;
    Sources?: Array<string> | null;
    Settings?: Array<SettingInputDto> | null;
    Filters?: Array<FilterInputDto> | null;
    Metadata?: {
        [key: string]: string;
    } | null;
    AdditionalTargetURLs?: Array<TargetUrlInputDto> | null;
};

export type BulkUpdateBackupsRequestDto = {
    BackupIDs: Array<string> | null;
};

export type BulkUpdateBackupsResponseDto = {
    UpdatedBackupIDs: Array<string> | null;
};

export type BulkUpdateBackupsResponseDtoResponseEnvelope = {
    Success: boolean;
    Error: string | null;
    StatusCode: string | null;
    Data?: BulkUpdateBackupsResponseDto;
};

export type ChangelogDto = {
    Version: string | null;
    Changelog: string | null;
};

export type CommandLineLogOutputDto = {
    Pagesize?: number;
    Offset?: number;
    Count?: number;
    Items?: Array<string> | null;
    Finished?: boolean;
    Started?: boolean;
};

export type CommandlineTaskStartedDto = {
    Status?: string | null;
    ID?: string | null;
};

export type ConnectedBackupDto = {
    ID: string | null;
    Name: string | null;
};

export type ConnectionStringDto = {
    ID: number;
    Name: string | null;
    Description: string | null;
    BaseUrl: string | null;
    CreatedAt: string;
    UpdatedAt: string;
    Backups: Array<ConnectedBackupDto> | null;
};

export type ConnectionStringDtoArrayResponseEnvelope = {
    Success: boolean;
    Error: string | null;
    StatusCode: string | null;
    Data?: Array<ConnectionStringDto> | null;
};

export type ConnectionStringDtoResponseEnvelope = {
    Success: boolean;
    Error: string | null;
    StatusCode: string | null;
    Data?: ConnectionStringDto;
};

export type CrashLogOutputDto = {
    Logdata?: string | null;
};

export type CreateBackupDto = {
    ID?: string | null;
    Temporary?: boolean;
};

export type CreateConnectionStringDto = {
    Name: string | null;
    Description: string | null;
    BaseUrl: string | null;
};

export type DayOfWeek = 'sun' | 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat';

export type DeleteBackupOutputDto = {
    Status?: string | null;
    Reason?: string | null;
    ID?: number | null;
};

export type DeleteVersionsRequestDto = {
    BackupId: string | null;
    Versions: Array<number> | null;
    AllowFullRemoval?: boolean | null;
    SuppressCompact?: boolean | null;
};

export type DestinationListRequestDto = {
    BackupId: string | null;
    ConnectionStringId?: number | null;
    DestinationUrl: string | null;
    DestinationType?: RemoteDestinationType;
    SourcePrefix?: string | null;
    Path: string | null;
    Offset: number | null;
    Limit: number | null;
};

export type DestinationListResponesContent = {
    Items: Array<DestinationListResponseItem> | null;
    Offset: number;
    HasMore: boolean;
};

export type DestinationListResponseDto = {
    Success: boolean;
    Error: string | null;
    StatusCode: string | null;
    Data?: DestinationListResponesContent;
};

export type DestinationListResponseItem = {
    Path: string | null;
    Size: number;
    Metadata: {
        [key: string]: string | null;
    } | null;
};

export type DestinationTestRequestDto = {
    DestinationUrl: string | null;
    BackupId?: string | null;
    ConnectionStringId?: number | null;
    Options: {
        [key: string]: string;
    } | null;
    AutoCreate: boolean;
    ReadOnlyTest?: boolean;
    DestinationType?: RemoteDestinationType;
    SourcePrefix?: string | null;
};

export type DestinationTestResponseDto = {
    Success: boolean;
    Error: string | null;
    StatusCode: string | null;
    Data?: DestinationTestResult;
};

export type DestinationTestResult = {
    FolderExists: boolean | null;
    FolderIsEmpty: boolean | null;
    FolderContainsBackupFiles: boolean | null;
    FolderContainsEncryptedBackupFiles: boolean | null;
    AfterConnect: boolean | null;
    HostCertificate: string | null;
    ReportedHostKey: string | null;
    AcceptedHostKey: string | null;
};

export type ExportArgsOnlyDto = {
    Backend?: string | null;
    Arguments?: Array<string> | null;
    Options?: Array<string> | null;
};

export type ExportCommandlineDto = {
    Command?: string | null;
};

export type FilesystemInput = {
    path?: string | null;
};

export type FilterDto = {
    Order: number;
    Include: boolean;
    Expression: string | null;
};

export type FilterGroupsDto = {
    FilterGroups?: {
        [key: string]: Array<string>;
    } | null;
};

export type FilterInputDto = {
    Order?: number;
    Include?: boolean;
    Expression?: string | null;
};

export type FolderStatusDto = {
    Path: string | null;
    Status: string | null;
    BackupName?: string | null;
    LastBackupTime?: string | null;
    BackupId?: string | null;
};

export type GetBackupResultDto = {
    Schedule?: ScheduleDto;
    Backup?: BackupDto;
    DisplayNames?: {
        [key: string]: string;
    } | null;
};

export type GetDbPathDto = {
    Exists?: boolean;
    Path?: string | null;
};

export type GetTaskStateDto = {
    Status?: string | null;
    ID?: number;
    TaskStarted?: string | null;
    TaskFinished?: string | null;
    ErrorMessage?: string | null;
    Exception?: string | null;
};

export type ICommandLineArgument = {
    Aliases?: Array<string> | null;
    LongDescription?: string | null;
    Name?: string | null;
    ShortDescription?: string | null;
    Type?: ArgumentType;
    ValidValues?: Array<string> | null;
    DefaultValue?: string | null;
    readonly Typename?: string | null;
    Deprecated?: boolean;
    DeprecationMessage?: string | null;
};

export type IDynamicModule = {
    readonly Key?: string | null;
    readonly Description?: string | null;
    readonly DisplayName?: string | null;
    readonly Options?: Array<ICommandLineArgument> | null;
    readonly Lookups?: {
        [key: string]: {
            [key: string]: string;
        } | null;
    } | null;
    readonly IsDeprecated?: boolean;
    readonly IsUntested?: boolean;
};

export type IListResultFileset = {
    readonly Version?: number;
    readonly IsFullBackup?: number;
    readonly Time?: string;
    readonly FileCount?: number;
    readonly FileSizes?: number;
    readonly Label?: string | null;
};

export type IProgressEventData = {
    readonly BackupID?: string | null;
    readonly TaskID?: number;
    readonly BackendAction?: string | null;
    readonly BackendPath?: string | null;
    readonly BackendFileSize?: number;
    readonly BackendFileProgress?: number;
    readonly BackendSpeed?: number;
    readonly BackendIsBlocking?: boolean;
    readonly CurrentFilename?: string | null;
    readonly CurrentFilesize?: number;
    readonly CurrentFileoffset?: number;
    readonly CurrentFilecomplete?: boolean;
    readonly Phase?: string | null;
    readonly OverallProgress?: number;
    readonly ProcessedFileCount?: number;
    readonly ProcessedFileSize?: number;
    readonly TotalFileCount?: number;
    readonly TotalFileSize?: number;
    readonly StillCounting?: boolean;
    readonly ActiveTransfers?: Array<ActiveTransfer> | null;
    readonly RemoteSyncDestinationIndex?: number;
    readonly RemoteSyncDestinationCount?: number;
    readonly EstimatedTimeToCompletion?: string | null;
};

export type IWebModule = {
    readonly SupportedCommands?: Array<ICommandLineArgument> | null;
    readonly Key?: string | null;
    readonly DisplayName?: string | null;
    readonly Description?: string | null;
};

export type ImportBackupFromTempDto = {
    BackupId?: string | null;
    ImportMetadata?: boolean;
    Direct?: boolean;
};

export type ImportBackupInputDto = {
    config?: string | null;
    cmdline?: boolean | null;
    import_metadata?: boolean | null;
    direct?: boolean | null;
    passphrase?: string | null;
    temporary?: boolean | null;
    replace_settings?: {
        [key: string]: string;
    } | null;
};

export type ImportBackupOutputDto = {
    Id?: string | null;
    data?: unknown;
};

export type Int64StringTuple = {
    Item1?: number;
    Item2?: string | null;
};

export type IsBackupActiveDto = {
    Status?: string | null;
    Active?: boolean;
};

export type IsDbUsedElsewhereDto = {
    inuse?: boolean;
};

export type IssueSigninTokenInputDto = {
    Password?: string | null;
};

export type LicenseDto = {
    Title: string | null;
    Url: string | null;
    License: string | null;
    Jsondata: string | null;
};

export type LicenseStatusDto = {
    IsConfigured: boolean;
    IsValid: boolean;
    IsInGracePeriod: boolean;
    ExpiresAt: string | null;
    ExpiresWithGraceAt: string | null;
    Features: {
        [key: string]: string;
    } | null;
};

export type ListBrokenFilesFileItem = {
    Path: string | null;
    Size: number;
};

export type ListBrokenFilesFilesetItem = {
    FilesetID: number;
    FilesetTime: string;
    Files: Array<ListBrokenFilesFileItem> | null;
};

export type ListBrokenFilesRequestDto = {
    BackupId: string | null;
    Filters?: Array<string> | null;
};

export type ListBrokenFilesResponseDto = {
    Success: boolean;
    Error: string | null;
    StatusCode: string | null;
    Data?: Array<ListBrokenFilesFilesetItem> | null;
    PageInfo: PageInfo;
};

export type ListFileVersionsItemDto = {
    Version: number;
    Time: string;
    Path: string | null;
    Size: number;
    IsDirectory: boolean;
    IsSymlink: boolean;
    LastModified: string;
};

export type ListFileVersionsOutputDto = {
    Success: boolean;
    Error: string | null;
    StatusCode: string | null;
    Data?: Array<ListFileVersionsItemDto> | null;
    PageInfo: PageInfo;
};

export type ListFileVersionsRequestDto = {
    PageSize: number | null;
    Page: number | null;
    BackupId: string | null;
    Paths: Array<string> | null;
};

export type ListFilesetsRequestDto = {
    BackupId: string | null;
    ForceRemoteListing?: boolean | null;
};

export type ListFilesetsResponseDto = {
    Success: boolean;
    Error: string | null;
    StatusCode: string | null;
    Data?: Array<ListFilesetsResponseItem> | null;
    PageInfo: PageInfo;
};

export type ListFilesetsResponseItem = {
    Version: number;
    Time: string;
    IsFullBackup: boolean | null;
    FileCount: number | null;
    FileSizes: number | null;
    Label?: string | null;
};

export type ListFolderContentItemDto = {
    Path: string | null;
    Size: number;
    IsDirectory: boolean;
    IsSymlink: boolean;
    LastModified: string;
    Metadata: {
        [key: string]: string | null;
    } | null;
};

export type ListFolderContentRequestDto = {
    PageSize: number | null;
    Page: number | null;
    BackupId: string | null;
    Paths: Array<string> | null;
    Time: string | null;
    ReturnExtended?: boolean | null;
};

export type ListFolderContentResponseDto = {
    Success: boolean;
    Error: string | null;
    StatusCode: string | null;
    Data?: Array<ListFolderContentItemDto> | null;
    PageInfo: PageInfo;
};

export type LiveControlState = 'Running' | 'Paused';

export type LocaleDto = {
    Code: string | null;
    EnglishName: string | null;
    DisplayName: string | null;
};

export type LogEntry = {
    When: string;
    ID: number;
    Message: string | null;
    Tag: string | null;
    MessageID: string | null;
    ExceptionID: string | null;
    Type: LogMessageType;
    Exception: string | null;
    BackupID: string | null;
    TaskID: string | null;
};

export type LogMessageType = 'ExplicitOnly' | 'Profiling' | 'Verbose' | 'Retry' | 'Information' | 'DryRun' | 'Warning' | 'Error';

export type LoginInputDto = {
    Password?: string | null;
    RememberMe?: boolean | null;
};

export type NotificationDto = {
    ID: number;
    Type: NotificationType;
    Title: string | null;
    Message: string | null;
    Exception: string | null;
    BackupID: string | null;
    Action: string | null;
    Timestamp: string;
    LogEntryID: string | null;
    MessageID: string | null;
    MessageLogTag: string | null;
};

export type NotificationType = 'Information' | 'Warning' | 'Error';

export type ObjectResponseEnvelope = {
    Success: boolean;
    Error: string | null;
    StatusCode: string | null;
    Data?: unknown;
};

export type OperationType = 'Backup' | 'Sync';

export type PageInfo = {
    Page?: number;
    PageSize?: number;
    Total?: number;
    Pages?: number;
};

export type PurgeBrokenFilesRequestDto = {
    BackupId: string | null;
};

export type RefreshTokenInputDto = {
    Nonce?: string | null;
};

export type RemoteControlStatusOutput = {
    CanEnable?: boolean;
    IsEnabled?: boolean;
    IsConnected?: boolean;
    IsRegistering?: boolean;
    IsRegisteringFaulted?: boolean;
    IsRegisteringCompleted?: boolean;
    RegistrationUrl?: string | null;
};

export type RemoteDestinationType = 'Backend' | 'SourceProvider' | 'RestoreDestinationProvider';

export type RemoteOperationInput = {
    path?: string | null;
    backupId?: string | null;
    connectionStringId?: number | null;
    sourcePrefix?: string | null;
};

export type RepairInputDto = {
    only_paths?: boolean | null;
    time?: string | null;
    version?: string | null;
    paths?: Array<string> | null;
    refresh_lock_info?: boolean | null;
};

export type RestoreInputDto = {
    paths?: Array<string> | null;
    passphrase?: string | null;
    time?: string | null;
    restore_path?: string | null;
    overwrite?: boolean | null;
    permissions?: boolean | null;
    skip_metadata?: boolean | null;
    connection_string_id?: number | null;
    source_prefix?: string | null;
};

export type RestoreTaskConfigElementDto = {
    BackupId: string | null;
    Name: string | null;
    TargetURLDisplay: string | null;
    Metadata: {
        [key: string]: string | null;
    } | null;
    DisplayNames: {
        [key: string]: string;
    } | null;
    AdditionalTargetUrls: Array<string> | null;
};

export type ScheduleDto = {
    ID: number;
    Tags: Array<string> | null;
    Time: string;
    Repeat: string | null;
    LastRun: string;
    Rule: string | null;
    AllowedDays: Array<DayOfWeek> | null;
};

export type ScheduleInputDto = {
    ID?: number;
    Tags?: Array<string> | null;
    Time?: string | null;
    Repeat?: string | null;
    LastRun?: string | null;
    Rule?: string | null;
    AllowedDays?: Array<DayOfWeek> | null;
};

export type SearchEntriesItemDto = {
    Version: number;
    Time: string;
    Path: string | null;
    Size: number;
    IsDirectory: boolean;
    IsSymlink: boolean;
    LastModified: string;
    Metadata: {
        [key: string]: string | null;
    } | null;
};

export type SearchEntriesRequestDto = {
    PageSize: number | null;
    Page: number | null;
    BackupId: string | null;
    Paths: Array<string> | null;
    Filters: Array<string> | null;
    Time?: string | null;
    ReturnExtended?: boolean | null;
    Version?: Array<number> | null;
    CaseSensitiveSearch?: boolean | null;
    SearchMetadata?: boolean | null;
};

export type SearchEntriesResponseDto = {
    Success: boolean;
    Error: string | null;
    StatusCode: string | null;
    Data?: Array<SearchEntriesItemDto> | null;
    PageInfo: PageInfo;
};

export type ServerStatusDto = {
    ActiveTask: Int64StringTuple;
    ProgramState: LiveControlState;
    SchedulerQueueIds: Array<Int64StringTuple> | null;
    ProposedSchedule: Array<StringDateTimeTuple> | null;
    HasWarning: boolean;
    HasError: boolean;
    SuggestedStatusIcon: SuggestedStatusIcon;
    EstimatedPauseEnd: string;
    LastEventID: number;
    LastDataUpdateID: number;
    LastNotificationUpdateID: number;
    UpdatedVersion: string | null;
    UpdaterState: UpdatePollerStates;
    UpdateDownloadLink: string | null;
    UpdateDownloadProgress: number;
    readonly Type?: string | null;
};

export type SetVersionLabelRequestDto = {
    BackupId: string | null;
    Version: number;
    Label?: string | null;
};

export type SetVersionLabelResponseDto = {
    Version: number;
    Time: string;
    Label: string | null;
};

export type SettingDto = {
    Filter: string | null;
    Name: string | null;
    Value: string | null;
    Argument: ICommandLineArgument;
};

export type SettingInputDto = {
    Filter?: string | null;
    Name: string | null;
    Value?: string | null;
};

export type SigninInputDto = {
    SigninToken?: string | null;
    RememberMe?: boolean | null;
};

export type SigninTokenOutputDto = {
    Token?: string | null;
};

export type SingleOperationTokenOutputDto = {
    Token?: string | null;
};

export type SpecialFolderDto = {
    ID: string | null;
    Path: string | null;
};

export type StartRegistrationInput = {
    RegistrationUrl?: string | null;
};

export type StringDateTimeTuple = {
    Item1?: string | null;
    Item2?: string;
};

export type SuggestedStatusIcon = 'Ready' | 'ReadyWarning' | 'ReadyError' | 'Paused' | 'Active' | 'ActivePaused' | 'Disconnected';

export type SystemInfoDto = {
    APIVersion: number;
    PasswordPlaceholder: string | null;
    ServerVersion: string | null;
    ServerVersionName: string | null;
    ServerVersionType: string | null;
    RemoteControlRegistrationUrl: string | null;
    RemoteControlDashboardUrl: string | null;
    StartedBy: string | null;
    DefaultUpdateChannel: string | null;
    DefaultUsageReportLevel: string | null;
    ServerTime: string;
    ServerTimeZone: string | null;
    OSType: string | null;
    OSVersion: string | null;
    DirectorySeparator: string;
    PathSeparator: string;
    CaseSensitiveFilesystem: boolean;
    MachineName: string | null;
    PackageTypeId: string | null;
    UserName: string | null;
    NewLine: string | null;
    CLRVersion: string | null;
    Options: Array<ICommandLineArgument> | null;
    ServerOnlyOptions: Array<ICommandLineArgument> | null;
    CompressionModules: Array<IDynamicModule> | null;
    EncryptionModules: Array<IDynamicModule> | null;
    BackendModules: Array<IDynamicModule> | null;
    GenericModules: Array<IDynamicModule> | null;
    WebModules: Array<IDynamicModule> | null;
    ConnectionModules: Array<IDynamicModule> | null;
    SourceProviderModules: Array<IDynamicModule> | null;
    RestoreDestinationProviderModules: Array<IDynamicModule> | null;
    ServerModules: Array<unknown> | null;
    SecretProviderModules: Array<IDynamicModule> | null;
    UsingAlternateUpdateURLs: boolean;
    LogLevels: Array<string> | null;
    SpecialFolders: Array<SpecialFolderDto> | null;
    BrowserLocale: LocaleDto;
    SupportedLocales: Array<LocaleDto> | null;
    BrowserLocaleSupported: boolean;
    TimeZones: Array<TimeZoneDto> | null;
    APIExtensions: Array<string> | null;
    APIScopes: Array<string> | null;
    DefaultOAuthURL: string | null;
    DefaultOAuthURLv2: string | null;
    PowerModeProviders: Array<string> | null;
    LocalLicenseStatus: LicenseStatusDto;
    RemoteLicenseStatus: LicenseStatusDto;
};

export type TargetUrlDto = {
    UrlKey: string | null;
    TargetUrl: string | null;
    Mode: string | null;
    Interval?: string | null;
    ConnectionStringID: number;
    Options: {
        [key: string]: unknown;
    } | null;
};

export type TargetUrlInputDto = {
    UrlKey?: string | null;
    TargetUrl: string | null;
    Mode?: string | null;
    Interval?: string | null;
    ConnectionStringID?: number;
    Options?: {
        [key: string]: unknown;
    } | null;
};

export type TaskStartedDto = {
    Status?: string | null;
    ID?: number;
};

export type TempDiskSpaceRequestDto = {
    BackupId?: string | null;
};

export type TempDiskSpaceResponseDto = {
    Success: boolean;
    Error: string | null;
    StatusCode: string | null;
    Data?: TempDiskSpaceResult;
};

export type TempDiskSpaceResult = {
    TempPath: string | null;
    FreeSpace: number | null;
    TotalSpace: number | null;
    DblockSize: number;
    RestoreCacheMax: number;
};

export type TestFilterRequestDto = {
    Paths?: Array<string> | null;
    Sources?: Array<string> | null;
    Filters?: Array<string> | null;
};

export type TestFilterResponseDto = {
    Success: boolean;
    Error: string | null;
    StatusCode: string | null;
    Data?: Array<TestFilterResponseItem> | null;
};

export type TestFilterResponseItem = {
    Path?: string | null;
    Included?: boolean;
    MatchedFilter?: string | null;
};

export type TimeZoneDto = {
    ID: string | null;
    DisplayName: string | null;
    CurrentUTCOffset: string | null;
};

export type TreeNodeDto = {
    text: string | null;
    id: string | null;
    cls: string | null;
    iconCls: string | null;
    check: boolean;
    leaf: boolean;
    resolvedpath: string | null;
    hidden: boolean;
    systemFile: boolean;
    temporary: boolean;
    symlink: boolean;
    fileSize: number;
};

export type UpdateCertificateInputDto = {
    Certificate?: string | null;
    Password?: string | null;
};

export type UpdateConnectionStringDto = {
    Name: string | null;
    Description: string | null;
    BaseUrl: string | null;
};

export type UpdateDbPathInputDto = {
    path?: string | null;
};

export type UpdatePollerStates = 'Waiting' | 'Checking' | 'Downloading';

export type WebModuleOutputDto = {
    Status?: string | null;
    Result?: {
        [key: string]: string;
    } | null;
};

export type BackupAndScheduleOutputDtoWritable = {
    Backup: BackupDtoWritable;
    Schedule: ScheduleDto;
};

export type BackupDtoWritable = {
    ID: string | null;
    ExternalID: string | null;
    Name: string | null;
    Description: string | null;
    Tags: Array<string> | null;
    TargetURL: string | null;
    ConnectionStringID?: number;
    OperationType?: OperationType;
    DBPath: string | null;
    DBPathExists: boolean;
    Sources: Array<string> | null;
    Settings: Array<SettingDtoWritable> | null;
    Filters: Array<FilterDto> | null;
    Metadata: {
        [key: string]: string;
    } | null;
    IsTemporary: boolean;
    IsUnencryptedOrPassphraseStored: boolean;
    AdditionalTargetURLs: Array<TargetUrlDto> | null;
};

export type GetBackupResultDtoWritable = {
    Schedule?: ScheduleDto;
    Backup?: BackupDtoWritable;
    DisplayNames?: {
        [key: string]: string;
    } | null;
};

export type ICommandLineArgumentWritable = {
    Aliases?: Array<string> | null;
    LongDescription?: string | null;
    Name?: string | null;
    ShortDescription?: string | null;
    Type?: ArgumentType;
    ValidValues?: Array<string> | null;
    DefaultValue?: string | null;
    Deprecated?: boolean;
    DeprecationMessage?: string | null;
};

export type IDynamicModuleWritable = {
    [key: string]: never;
};

export type IProgressEventDataWritable = {
    [key: string]: never;
};

export type IWebModuleWritable = {
    [key: string]: never;
};

export type ServerStatusDtoWritable = {
    ActiveTask: Int64StringTuple;
    ProgramState: LiveControlState;
    SchedulerQueueIds: Array<Int64StringTuple> | null;
    ProposedSchedule: Array<StringDateTimeTuple> | null;
    HasWarning: boolean;
    HasError: boolean;
    SuggestedStatusIcon: SuggestedStatusIcon;
    EstimatedPauseEnd: string;
    LastEventID: number;
    LastDataUpdateID: number;
    LastNotificationUpdateID: number;
    UpdatedVersion: string | null;
    UpdaterState: UpdatePollerStates;
    UpdateDownloadLink: string | null;
    UpdateDownloadProgress: number;
};

export type SettingDtoWritable = {
    Filter: string | null;
    Name: string | null;
    Value: string | null;
    Argument: ICommandLineArgumentWritable;
};

export type SystemInfoDtoWritable = {
    APIVersion: number;
    PasswordPlaceholder: string | null;
    ServerVersion: string | null;
    ServerVersionName: string | null;
    ServerVersionType: string | null;
    RemoteControlRegistrationUrl: string | null;
    RemoteControlDashboardUrl: string | null;
    StartedBy: string | null;
    DefaultUpdateChannel: string | null;
    DefaultUsageReportLevel: string | null;
    ServerTime: string;
    ServerTimeZone: string | null;
    OSType: string | null;
    OSVersion: string | null;
    DirectorySeparator: string;
    PathSeparator: string;
    CaseSensitiveFilesystem: boolean;
    MachineName: string | null;
    PackageTypeId: string | null;
    UserName: string | null;
    NewLine: string | null;
    CLRVersion: string | null;
    Options: Array<ICommandLineArgumentWritable> | null;
    ServerOnlyOptions: Array<ICommandLineArgumentWritable> | null;
    CompressionModules: Array<IDynamicModuleWritable> | null;
    EncryptionModules: Array<IDynamicModuleWritable> | null;
    BackendModules: Array<IDynamicModuleWritable> | null;
    GenericModules: Array<IDynamicModuleWritable> | null;
    WebModules: Array<IDynamicModuleWritable> | null;
    ConnectionModules: Array<IDynamicModuleWritable> | null;
    SourceProviderModules: Array<IDynamicModuleWritable> | null;
    RestoreDestinationProviderModules: Array<IDynamicModuleWritable> | null;
    ServerModules: Array<unknown> | null;
    SecretProviderModules: Array<IDynamicModuleWritable> | null;
    UsingAlternateUpdateURLs: boolean;
    LogLevels: Array<string> | null;
    SpecialFolders: Array<SpecialFolderDto> | null;
    BrowserLocale: LocaleDto;
    SupportedLocales: Array<LocaleDto> | null;
    BrowserLocaleSupported: boolean;
    TimeZones: Array<TimeZoneDto> | null;
    APIExtensions: Array<string> | null;
    APIScopes: Array<string> | null;
    DefaultOAuthURL: string | null;
    DefaultOAuthURLv2: string | null;
    PowerModeProviders: Array<string> | null;
    LocalLicenseStatus: LicenseStatusDto;
    RemoteLicenseStatus: LicenseStatusDto;
};

export type GetApiV1CommandlineData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/commandline';
};

export type GetApiV1CommandlineResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetApiV1CommandlineResponse = GetApiV1CommandlineResponses[keyof GetApiV1CommandlineResponses];

export type PostApiV1CommandlineData = {
    body: Array<string>;
    path?: never;
    query?: never;
    url: '/api/v1/commandline';
};

export type PostApiV1CommandlineResponses = {
    /**
     * OK
     */
    200: CommandlineTaskStartedDto;
};

export type PostApiV1CommandlineResponse = PostApiV1CommandlineResponses[keyof PostApiV1CommandlineResponses];

export type GetApiV2ConnectionStringsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v2/connection-strings';
};

export type GetApiV2ConnectionStringsResponses = {
    /**
     * OK
     */
    200: ConnectionStringDtoArrayResponseEnvelope;
};

export type GetApiV2ConnectionStringsResponse = GetApiV2ConnectionStringsResponses[keyof GetApiV2ConnectionStringsResponses];

export type PostApiV2ConnectionStringsData = {
    body: CreateConnectionStringDto;
    path?: never;
    query?: never;
    url: '/api/v2/connection-strings';
};

export type PostApiV2ConnectionStringsResponses = {
    /**
     * OK
     */
    200: ConnectionStringDtoResponseEnvelope;
};

export type PostApiV2ConnectionStringsResponse = PostApiV2ConnectionStringsResponses[keyof PostApiV2ConnectionStringsResponses];

export type DeleteApiV2ConnectionStringByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v2/connection-string/{id}';
};

export type DeleteApiV2ConnectionStringByIdResponses = {
    /**
     * OK
     */
    200: ObjectResponseEnvelope;
};

export type DeleteApiV2ConnectionStringByIdResponse = DeleteApiV2ConnectionStringByIdResponses[keyof DeleteApiV2ConnectionStringByIdResponses];

export type GetApiV2ConnectionStringByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v2/connection-string/{id}';
};

export type GetApiV2ConnectionStringByIdResponses = {
    /**
     * OK
     */
    200: ConnectionStringDtoResponseEnvelope;
};

export type GetApiV2ConnectionStringByIdResponse = GetApiV2ConnectionStringByIdResponses[keyof GetApiV2ConnectionStringByIdResponses];

export type PutApiV2ConnectionStringByIdData = {
    body: UpdateConnectionStringDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v2/connection-string/{id}';
};

export type PutApiV2ConnectionStringByIdResponses = {
    /**
     * OK
     */
    200: ConnectionStringDtoResponseEnvelope;
};

export type PutApiV2ConnectionStringByIdResponse = PutApiV2ConnectionStringByIdResponses[keyof PutApiV2ConnectionStringByIdResponses];

export type PostApiV2ConnectionStringByIdUpdateBackupsData = {
    body: BulkUpdateBackupsRequestDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v2/connection-string/{id}/update-backups';
};

export type PostApiV2ConnectionStringByIdUpdateBackupsResponses = {
    /**
     * OK
     */
    200: BulkUpdateBackupsResponseDtoResponseEnvelope;
};

export type PostApiV2ConnectionStringByIdUpdateBackupsResponse = PostApiV2ConnectionStringByIdUpdateBackupsResponses[keyof PostApiV2ConnectionStringByIdUpdateBackupsResponses];

export type GetApiV1AcknowledgementsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/acknowledgements';
};

export type GetApiV1AcknowledgementsResponses = {
    /**
     * OK
     */
    200: AcknowlegdementDto;
};

export type GetApiV1AcknowledgementsResponse = GetApiV1AcknowledgementsResponses[keyof GetApiV1AcknowledgementsResponses];

export type PostApiV1AuthRefreshData = {
    body?: RefreshTokenInputDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type PostApiV1AuthRefreshResponses = {
    /**
     * OK
     */
    200: AccessTokenOutputDto;
};

export type PostApiV1AuthRefreshResponse = PostApiV1AuthRefreshResponses[keyof PostApiV1AuthRefreshResponses];

export type PostApiV1AuthSigninData = {
    body: SigninInputDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/signin';
};

export type PostApiV1AuthSigninResponses = {
    /**
     * OK
     */
    200: AccessTokenOutputDto;
};

export type PostApiV1AuthSigninResponse = PostApiV1AuthSigninResponses[keyof PostApiV1AuthSigninResponses];

export type PostApiV1AuthLoginData = {
    body: LoginInputDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type PostApiV1AuthLoginResponses = {
    /**
     * OK
     */
    200: AccessTokenOutputDto;
};

export type PostApiV1AuthLoginResponse = PostApiV1AuthLoginResponses[keyof PostApiV1AuthLoginResponses];

export type PostApiV1AuthIssuesignintokenData = {
    body: IssueSigninTokenInputDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/issuesignintoken';
};

export type PostApiV1AuthIssuesignintokenResponses = {
    /**
     * OK
     */
    200: SigninTokenOutputDto;
};

export type PostApiV1AuthIssuesignintokenResponse = PostApiV1AuthIssuesignintokenResponses[keyof PostApiV1AuthIssuesignintokenResponses];

export type PostApiV1AuthRefreshLogoutData = {
    body?: RefreshTokenInputDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh/logout';
};

export type PostApiV1AuthRefreshLogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1AuthIssuetokenByOperationData = {
    body?: never;
    path: {
        operation: string;
    };
    query?: never;
    url: '/api/v1/auth/issuetoken/{operation}';
};

export type PostApiV1AuthIssuetokenByOperationResponses = {
    /**
     * OK
     */
    200: SingleOperationTokenOutputDto;
};

export type PostApiV1AuthIssuetokenByOperationResponse = PostApiV1AuthIssuetokenByOperationResponses[keyof PostApiV1AuthIssuetokenByOperationResponses];

export type PostApiV1AuthIssueForeverTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/issue-forever-token';
};

export type PostApiV1AuthIssueForeverTokenResponses = {
    /**
     * OK
     */
    200: AccessTokenOutputDto;
};

export type PostApiV1AuthIssueForeverTokenResponse = PostApiV1AuthIssueForeverTokenResponses[keyof PostApiV1AuthIssueForeverTokenResponses];

export type PostApiV1AuthStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/status';
};

export type PostApiV1AuthStatusResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1BackupdefaultsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/backupdefaults';
};

export type GetApiV1BackupdefaultsResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetApiV1BackupdefaultsResponse = GetApiV1BackupdefaultsResponses[keyof GetApiV1BackupdefaultsResponses];

export type GetApiV1BackupsData = {
    body?: never;
    path?: never;
    query?: {
        orderBy?: string;
    };
    url: '/api/v1/backups';
};

export type GetApiV1BackupsResponses = {
    /**
     * OK
     */
    200: Array<BackupAndScheduleOutputDto>;
};

export type GetApiV1BackupsResponse = GetApiV1BackupsResponses[keyof GetApiV1BackupsResponses];

export type PostApiV1BackupsData = {
    body: BackupAndScheduleInputDto;
    path?: never;
    query?: {
        temporary?: boolean;
        existingdb?: boolean;
    };
    url: '/api/v1/backups';
};

export type PostApiV1BackupsResponses = {
    /**
     * OK
     */
    200: CreateBackupDto;
};

export type PostApiV1BackupsResponse = PostApiV1BackupsResponses[keyof PostApiV1BackupsResponses];

export type PostApiV1BackupsImportData = {
    body: ImportBackupInputDto;
    path?: never;
    query?: never;
    url: '/api/v1/backups/import';
};

export type PostApiV1BackupsImportResponses = {
    /**
     * OK
     */
    200: ImportBackupOutputDto;
};

export type PostApiV1BackupsImportResponse = PostApiV1BackupsImportResponses[keyof PostApiV1BackupsImportResponses];

export type GetApiV1BugreportByReportidData = {
    body?: never;
    path: {
        reportid: number;
    };
    query: {
        token: string;
    };
    url: '/api/v1/bugreport/{reportid}';
};

export type GetApiV1BugreportByReportidResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ChangelogData = {
    body?: never;
    path?: never;
    query?: {
        'from-update'?: boolean;
    };
    url: '/api/v1/changelog';
};

export type GetApiV1ChangelogResponses = {
    /**
     * OK
     */
    200: ChangelogDto;
};

export type GetApiV1ChangelogResponse = GetApiV1ChangelogResponses[keyof GetApiV1ChangelogResponses];

export type GetApiV1CommandlineByRunidData = {
    body?: never;
    path: {
        runid: string;
    };
    query?: {
        offset?: number;
        pagesize?: number;
    };
    url: '/api/v1/commandline/{runid}';
};

export type GetApiV1CommandlineByRunidResponses = {
    /**
     * OK
     */
    200: CommandLineLogOutputDto;
};

export type GetApiV1CommandlineByRunidResponse = GetApiV1CommandlineByRunidResponses[keyof GetApiV1CommandlineByRunidResponses];

export type PostApiV1CommandlineByRunidAbortData = {
    body?: never;
    path: {
        runid: string;
    };
    query?: never;
    url: '/api/v1/commandline/{runid}/abort';
};

export type PostApiV1CommandlineByRunidAbortResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1FilesystemData = {
    body: FilesystemInput;
    path?: never;
    query?: {
        onlyFolders?: boolean;
        showHidden?: boolean;
    };
    url: '/api/v1/filesystem';
};

export type PostApiV1FilesystemResponses = {
    /**
     * OK
     */
    200: Array<TreeNodeDto>;
};

export type PostApiV1FilesystemResponse = PostApiV1FilesystemResponses[keyof PostApiV1FilesystemResponses];

export type PostApiV1FilesystemValidateData = {
    body: FilesystemInput;
    path?: never;
    query?: never;
    url: '/api/v1/filesystem/validate';
};

export type PostApiV1FilesystemValidateResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1FolderstatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/folderstatus';
};

export type GetApiV1FolderstatusResponses = {
    /**
     * OK
     */
    200: Array<FolderStatusDto>;
};

export type GetApiV1FolderstatusResponse = GetApiV1FolderstatusResponses[keyof GetApiV1FolderstatusResponses];

export type GetApiV1FolderstatusByPathData = {
    body?: never;
    path: {
        path: string;
    };
    query?: never;
    url: '/api/v1/folderstatus/{path}';
};

export type GetApiV1FolderstatusByPathResponses = {
    /**
     * OK
     */
    200: FolderStatusDto;
};

export type GetApiV1FolderstatusByPathResponse = GetApiV1FolderstatusByPathResponses[keyof GetApiV1FolderstatusByPathResponses];

export type GetApiV1LicensesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/licenses';
};

export type GetApiV1LicensesResponses = {
    /**
     * OK
     */
    200: Array<LicenseDto>;
};

export type GetApiV1LicensesResponse = GetApiV1LicensesResponses[keyof GetApiV1LicensesResponses];

export type GetApiV1LogdataPollData = {
    body?: never;
    path?: never;
    query: {
        level: LogMessageType;
        id: number;
        pagesize?: number;
    };
    url: '/api/v1/logdata/poll';
};

export type GetApiV1LogdataPollResponses = {
    /**
     * OK
     */
    200: Array<LogEntry>;
};

export type GetApiV1LogdataPollResponse = GetApiV1LogdataPollResponses[keyof GetApiV1LogdataPollResponses];

export type GetApiV1LogdataLogData = {
    body?: never;
    path?: never;
    query?: {
        offset?: number;
        pagesize?: number;
    };
    url: '/api/v1/logdata/log';
};

export type GetApiV1LogdataLogResponses = {
    /**
     * OK
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetApiV1LogdataLogResponse = GetApiV1LogdataLogResponses[keyof GetApiV1LogdataLogResponses];

export type GetApiV1LogdataCrashlogData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/logdata/crashlog';
};

export type GetApiV1LogdataCrashlogResponses = {
    /**
     * OK
     */
    200: CrashLogOutputDto;
};

export type GetApiV1LogdataCrashlogResponse = GetApiV1LogdataCrashlogResponses[keyof GetApiV1LogdataCrashlogResponses];

export type DeleteApiV1NotificationByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/notification/{id}';
};

export type DeleteApiV1NotificationByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1NotificationByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/notification/{id}';
};

export type GetApiV1NotificationByIdResponses = {
    /**
     * OK
     */
    200: NotificationDto;
};

export type GetApiV1NotificationByIdResponse = GetApiV1NotificationByIdResponses[keyof GetApiV1NotificationByIdResponses];

export type GetApiV1NotificationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/notifications';
};

export type GetApiV1NotificationsResponses = {
    /**
     * OK
     */
    200: Array<NotificationDto>;
};

export type GetApiV1NotificationsResponse = GetApiV1NotificationsResponses[keyof GetApiV1NotificationsResponses];

export type GetApiV1ProgressstateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/progressstate';
};

export type GetApiV1ProgressstateResponses = {
    /**
     * OK
     */
    200: IProgressEventData;
};

export type GetApiV1ProgressstateResponse = GetApiV1ProgressstateResponses[keyof GetApiV1ProgressstateResponses];

export type GetApiV1RemotecontrolStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/remotecontrol/status';
};

export type GetApiV1RemotecontrolStatusResponses = {
    /**
     * OK
     */
    200: RemoteControlStatusOutput;
};

export type GetApiV1RemotecontrolStatusResponse = GetApiV1RemotecontrolStatusResponses[keyof GetApiV1RemotecontrolStatusResponses];

export type PostApiV1RemoteoperationDbpathData = {
    body: RemoteOperationInput;
    path?: never;
    query?: never;
    url: '/api/v1/remoteoperation/dbpath';
};

export type PostApiV1RemoteoperationDbpathResponses = {
    /**
     * OK
     */
    200: GetDbPathDto;
};

export type PostApiV1RemoteoperationDbpathResponse = PostApiV1RemoteoperationDbpathResponses[keyof PostApiV1RemoteoperationDbpathResponses];

export type PostApiV1RemoteoperationTestData = {
    body: RemoteOperationInput;
    path?: never;
    query?: {
        autocreate?: boolean;
        readOnlyTest?: boolean;
        type?: RemoteDestinationType;
    };
    url: '/api/v1/remoteoperation/test';
};

export type PostApiV1RemoteoperationTestResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1RemoteoperationCreateData = {
    body: RemoteOperationInput;
    path?: never;
    query?: never;
    url: '/api/v1/remoteoperation/create';
};

export type PostApiV1RemoteoperationCreateResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ServersettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/serversettings';
};

export type GetApiV1ServersettingsResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type GetApiV1ServersettingsResponse = GetApiV1ServersettingsResponses[keyof GetApiV1ServersettingsResponses];

export type PatchApiV1ServersettingsData = {
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/v1/serversettings';
};

export type PatchApiV1ServersettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ServersettingByKeyData = {
    body?: never;
    path: {
        key: string;
    };
    query?: never;
    url: '/api/v1/serversetting/{key}';
};

export type GetApiV1ServersettingByKeyResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetApiV1ServersettingByKeyResponse = GetApiV1ServersettingByKeyResponses[keyof GetApiV1ServersettingByKeyResponses];

export type PutApiV1ServersettingByKeyData = {
    body: string;
    path: {
        key: string;
    };
    query?: never;
    url: '/api/v1/serversetting/{key}';
};

export type PutApiV1ServersettingByKeyResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ServerstateData = {
    body?: never;
    path?: never;
    query?: {
        lastEventId?: number;
        longpoll?: boolean;
        duration?: string;
    };
    url: '/api/v1/serverstate';
};

export type GetApiV1ServerstateResponses = {
    /**
     * OK
     */
    200: ServerStatusDto;
};

export type GetApiV1ServerstateResponse = GetApiV1ServerstateResponses[keyof GetApiV1ServerstateResponses];

export type PostApiV1ServerstatePauseData = {
    body?: never;
    path?: never;
    query?: {
        duration?: string;
        pauseTransfers?: boolean;
    };
    url: '/api/v1/serverstate/pause';
};

export type PostApiV1ServerstatePauseResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1ServerstateResumeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/serverstate/resume';
};

export type PostApiV1ServerstateResumeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1SysteminfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/systeminfo';
};

export type GetApiV1SysteminfoResponses = {
    /**
     * OK
     */
    200: SystemInfoDto;
};

export type GetApiV1SysteminfoResponse = GetApiV1SysteminfoResponses[keyof GetApiV1SysteminfoResponses];

export type GetApiV1SysteminfoFiltergroupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/systeminfo/filtergroups';
};

export type GetApiV1SysteminfoFiltergroupsResponses = {
    /**
     * OK
     */
    200: FilterGroupsDto;
};

export type GetApiV1SysteminfoFiltergroupsResponse = GetApiV1SysteminfoFiltergroupsResponses[keyof GetApiV1SysteminfoFiltergroupsResponses];

export type GetApiV1TasksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tasks';
};

export type GetApiV1TasksResponses = {
    /**
     * OK
     */
    200: Array<GetTaskStateDto>;
};

export type GetApiV1TasksResponse = GetApiV1TasksResponses[keyof GetApiV1TasksResponses];

export type GetApiV1TaskByTaskidData = {
    body?: never;
    path: {
        taskid: number;
    };
    query?: never;
    url: '/api/v1/task/{taskid}';
};

export type GetApiV1TaskByTaskidResponses = {
    /**
     * OK
     */
    200: GetTaskStateDto;
};

export type GetApiV1TaskByTaskidResponse = GetApiV1TaskByTaskidResponses[keyof GetApiV1TaskByTaskidResponses];

export type PostApiV1TaskByTaskidStopData = {
    body?: never;
    path: {
        taskid: number;
    };
    query?: never;
    url: '/api/v1/task/{taskid}/stop';
};

export type PostApiV1TaskByTaskidStopResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1TaskByTaskidAbortData = {
    body?: never;
    path: {
        taskid: number;
    };
    query?: never;
    url: '/api/v1/task/{taskid}/abort';
};

export type PostApiV1TaskByTaskidAbortResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1UisettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/uisettings';
};

export type GetApiV1UisettingsResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetApiV1UisettingsResponse = GetApiV1UisettingsResponses[keyof GetApiV1UisettingsResponses];

export type PostApiV1UisettingsData = {
    body: UpdateCertificateInputDto;
    path?: never;
    query?: never;
    url: '/api/v1/uisettings';
};

export type PostApiV1UisettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1UisettingsBySchemeData = {
    body?: never;
    path: {
        scheme: string;
    };
    query?: never;
    url: '/api/v1/uisettings/{scheme}';
};

export type GetApiV1UisettingsBySchemeResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type GetApiV1UisettingsBySchemeResponse = GetApiV1UisettingsBySchemeResponses[keyof GetApiV1UisettingsBySchemeResponses];

export type PatchApiV1UisettingsBySchemeData = {
    body: {
        [key: string]: string;
    };
    path: {
        scheme: string;
    };
    query?: never;
    url: '/api/v1/uisettings/{scheme}';
};

export type PatchApiV1UisettingsBySchemeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1UpdatesCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/updates/check';
};

export type PostApiV1UpdatesCheckResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1WebmoduleByModulekeyData = {
    body: {
        [key: string]: string;
    };
    path: {
        modulekey: string;
    };
    query?: never;
    url: '/api/v1/webmodule/{modulekey}';
};

export type PostApiV1WebmoduleByModulekeyResponses = {
    /**
     * OK
     */
    200: WebModuleOutputDto;
};

export type PostApiV1WebmoduleByModulekeyResponse = PostApiV1WebmoduleByModulekeyResponses[keyof PostApiV1WebmoduleByModulekeyResponses];

export type DeleteApiV1BackupByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        'delete-remote-files'?: boolean;
        'delete-local-db'?: boolean;
        force?: boolean;
    };
    url: '/api/v1/backup/{id}';
};

export type DeleteApiV1BackupByIdResponses = {
    /**
     * OK
     */
    200: DeleteBackupOutputDto;
};

export type DeleteApiV1BackupByIdResponse = DeleteApiV1BackupByIdResponses[keyof DeleteApiV1BackupByIdResponses];

export type GetApiV1BackupByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/backup/{id}';
};

export type GetApiV1BackupByIdResponses = {
    /**
     * OK
     */
    200: GetBackupResultDto;
};

export type GetApiV1BackupByIdResponse = GetApiV1BackupByIdResponses[keyof GetApiV1BackupByIdResponses];

export type PutApiV1BackupByIdData = {
    body: BackupAndScheduleInputDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/backup/{id}';
};

export type PutApiV1BackupByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1BackupByIdFilesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        filter?: string;
        time?: string;
        'all-versions'?: boolean;
        'prefix-only'?: boolean;
        'folder-contents'?: boolean;
    };
    url: '/api/v1/backup/{id}/files';
};

export type GetApiV1BackupByIdFilesResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetApiV1BackupByIdFilesResponse = GetApiV1BackupByIdFilesResponses[keyof GetApiV1BackupByIdFilesResponses];

export type GetApiV1BackupByIdLogData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        offset?: number;
        pagesize?: number;
    };
    url: '/api/v1/backup/{id}/log';
};

export type GetApiV1BackupByIdLogResponses = {
    /**
     * OK
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetApiV1BackupByIdLogResponse = GetApiV1BackupByIdLogResponses[keyof GetApiV1BackupByIdLogResponses];

export type GetApiV1BackupByIdRemotelogData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        offset?: number;
        pagesize?: number;
    };
    url: '/api/v1/backup/{id}/remotelog';
};

export type GetApiV1BackupByIdRemotelogResponses = {
    /**
     * OK
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetApiV1BackupByIdRemotelogResponse = GetApiV1BackupByIdRemotelogResponses[keyof GetApiV1BackupByIdRemotelogResponses];

export type GetApiV1BackupByIdFilesetsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        'include-metadata'?: boolean;
        'from-remote-only'?: boolean;
    };
    url: '/api/v1/backup/{id}/filesets';
};

export type GetApiV1BackupByIdFilesetsResponses = {
    /**
     * OK
     */
    200: Array<IListResultFileset>;
};

export type GetApiV1BackupByIdFilesetsResponse = GetApiV1BackupByIdFilesetsResponses[keyof GetApiV1BackupByIdFilesetsResponses];

export type GetApiV1BackupByIdExportArgsonlyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        'export-passwords'?: boolean;
        passphrase?: string;
    };
    url: '/api/v1/backup/{id}/export-argsonly';
};

export type GetApiV1BackupByIdExportArgsonlyResponses = {
    /**
     * OK
     */
    200: ExportArgsOnlyDto;
};

export type GetApiV1BackupByIdExportArgsonlyResponse = GetApiV1BackupByIdExportArgsonlyResponses[keyof GetApiV1BackupByIdExportArgsonlyResponses];

export type GetApiV1BackupByIdExportCmdlineData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        'export-passwords'?: boolean;
        passphrase?: string;
    };
    url: '/api/v1/backup/{id}/export-cmdline';
};

export type GetApiV1BackupByIdExportCmdlineResponses = {
    /**
     * OK
     */
    200: ExportCommandlineDto;
};

export type GetApiV1BackupByIdExportCmdlineResponse = GetApiV1BackupByIdExportCmdlineResponses[keyof GetApiV1BackupByIdExportCmdlineResponses];

export type GetApiV1BackupByIdExportData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        'export-passwords'?: boolean;
        passphrase?: string;
        token: string;
    };
    url: '/api/v1/backup/{id}/export';
};

export type GetApiV1BackupByIdExportResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1BackupByIdIsdbusedelsewhereData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/backup/{id}/isdbusedelsewhere';
};

export type GetApiV1BackupByIdIsdbusedelsewhereResponses = {
    /**
     * OK
     */
    200: IsDbUsedElsewhereDto;
};

export type GetApiV1BackupByIdIsdbusedelsewhereResponse = GetApiV1BackupByIdIsdbusedelsewhereResponses[keyof GetApiV1BackupByIdIsdbusedelsewhereResponses];

export type GetApiV1BackupByIdIsactiveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/backup/{id}/isactive';
};

export type GetApiV1BackupByIdIsactiveResponses = {
    /**
     * OK
     */
    200: IsBackupActiveDto;
};

export type GetApiV1BackupByIdIsactiveResponse = GetApiV1BackupByIdIsactiveResponses[keyof GetApiV1BackupByIdIsactiveResponses];

export type PostApiV1BackupByIdDeletedbData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/backup/{id}/deletedb';
};

export type PostApiV1BackupByIdDeletedbResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1BackupByIdMovedbData = {
    body: UpdateDbPathInputDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/backup/{id}/movedb';
};

export type PostApiV1BackupByIdMovedbResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1BackupByIdUpdatedbData = {
    body: UpdateDbPathInputDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/backup/{id}/updatedb';
};

export type PostApiV1BackupByIdUpdatedbResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1BackupByIdRestoreData = {
    body: RestoreInputDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/backup/{id}/restore';
};

export type PostApiV1BackupByIdRestoreResponses = {
    /**
     * OK
     */
    200: TaskStartedDto;
};

export type PostApiV1BackupByIdRestoreResponse = PostApiV1BackupByIdRestoreResponses[keyof PostApiV1BackupByIdRestoreResponses];

export type PostApiV1BackupByIdCreatereportData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/backup/{id}/createreport';
};

export type PostApiV1BackupByIdCreatereportResponses = {
    /**
     * OK
     */
    200: TaskStartedDto;
};

export type PostApiV1BackupByIdCreatereportResponse = PostApiV1BackupByIdCreatereportResponses[keyof PostApiV1BackupByIdCreatereportResponses];

export type PostApiV1BackupByIdRepairData = {
    body?: RepairInputDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/backup/{id}/repair';
};

export type PostApiV1BackupByIdRepairResponses = {
    /**
     * OK
     */
    200: TaskStartedDto;
};

export type PostApiV1BackupByIdRepairResponse = PostApiV1BackupByIdRepairResponses[keyof PostApiV1BackupByIdRepairResponses];

export type PostApiV1BackupByIdRepairupdateData = {
    body?: RepairInputDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/backup/{id}/repairupdate';
};

export type PostApiV1BackupByIdRepairupdateResponses = {
    /**
     * OK
     */
    200: TaskStartedDto;
};

export type PostApiV1BackupByIdRepairupdateResponse = PostApiV1BackupByIdRepairupdateResponses[keyof PostApiV1BackupByIdRepairupdateResponses];

export type PostApiV1BackupByIdVacuumData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/backup/{id}/vacuum';
};

export type PostApiV1BackupByIdVacuumResponses = {
    /**
     * OK
     */
    200: TaskStartedDto;
};

export type PostApiV1BackupByIdVacuumResponse = PostApiV1BackupByIdVacuumResponses[keyof PostApiV1BackupByIdVacuumResponses];

export type PostApiV1BackupByIdVerifyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/backup/{id}/verify';
};

export type PostApiV1BackupByIdVerifyResponses = {
    /**
     * OK
     */
    200: TaskStartedDto;
};

export type PostApiV1BackupByIdVerifyResponse = PostApiV1BackupByIdVerifyResponses[keyof PostApiV1BackupByIdVerifyResponses];

export type PostApiV1BackupByIdCompactData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/backup/{id}/compact';
};

export type PostApiV1BackupByIdCompactResponses = {
    /**
     * OK
     */
    200: TaskStartedDto;
};

export type PostApiV1BackupByIdCompactResponse = PostApiV1BackupByIdCompactResponses[keyof PostApiV1BackupByIdCompactResponses];

export type PostApiV1BackupByIdStartData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        skipQueue?: boolean;
    };
    url: '/api/v1/backup/{id}/start';
};

export type PostApiV1BackupByIdStartResponses = {
    /**
     * OK
     */
    200: TaskStartedDto;
};

export type PostApiV1BackupByIdStartResponse = PostApiV1BackupByIdStartResponses[keyof PostApiV1BackupByIdStartResponses];

export type PostApiV1BackupByIdRunData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        skipQueue?: boolean;
    };
    url: '/api/v1/backup/{id}/run';
};

export type PostApiV1BackupByIdRunResponses = {
    /**
     * OK
     */
    200: TaskStartedDto;
};

export type PostApiV1BackupByIdRunResponse = PostApiV1BackupByIdRunResponses[keyof PostApiV1BackupByIdRunResponses];

export type PostApiV1BackupByIdReportRemoteSizeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/backup/{id}/report-remote-size';
};

export type PostApiV1BackupByIdReportRemoteSizeResponses = {
    /**
     * OK
     */
    200: TaskStartedDto;
};

export type PostApiV1BackupByIdReportRemoteSizeResponse = PostApiV1BackupByIdReportRemoteSizeResponses[keyof PostApiV1BackupByIdReportRemoteSizeResponses];

export type PostApiV1BackupByIdCopytotempData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/backup/{id}/copytotemp';
};

export type PostApiV1BackupByIdCopytotempResponses = {
    /**
     * OK
     */
    200: CreateBackupDto;
};

export type PostApiV1BackupByIdCopytotempResponse = PostApiV1BackupByIdCopytotempResponses[keyof PostApiV1BackupByIdCopytotempResponses];

export type PostApiV1BackupByIdRestoreTaskConfigData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/backup/{id}/restore-task-config';
};

export type PostApiV1BackupByIdRestoreTaskConfigResponses = {
    /**
     * OK
     */
    200: Array<RestoreTaskConfigElementDto>;
};

export type PostApiV1BackupByIdRestoreTaskConfigResponse = PostApiV1BackupByIdRestoreTaskConfigResponses[keyof PostApiV1BackupByIdRestoreTaskConfigResponses];

export type PostApiV1BackupByIdImportfromtempData = {
    body: ImportBackupFromTempDto;
    path?: never;
    query?: never;
    url: '/api/v1/backup/{id}/importfromtemp';
};

export type PostApiV1BackupByIdImportfromtempResponses = {
    /**
     * OK
     */
    200: ImportBackupOutputDto;
};

export type PostApiV1BackupByIdImportfromtempResponse = PostApiV1BackupByIdImportfromtempResponses[keyof PostApiV1BackupByIdImportfromtempResponses];

export type PostApiV1RemotecontrolEnableData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/remotecontrol/enable';
};

export type PostApiV1RemotecontrolEnableResponses = {
    /**
     * OK
     */
    200: RemoteControlStatusOutput;
};

export type PostApiV1RemotecontrolEnableResponse = PostApiV1RemotecontrolEnableResponses[keyof PostApiV1RemotecontrolEnableResponses];

export type PostApiV1RemotecontrolDisableData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/remotecontrol/disable';
};

export type PostApiV1RemotecontrolDisableResponses = {
    /**
     * OK
     */
    200: RemoteControlStatusOutput;
};

export type PostApiV1RemotecontrolDisableResponse = PostApiV1RemotecontrolDisableResponses[keyof PostApiV1RemotecontrolDisableResponses];

export type DeleteApiV1RemotecontrolRegistrationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/remotecontrol/registration';
};

export type DeleteApiV1RemotecontrolRegistrationResponses = {
    /**
     * OK
     */
    200: RemoteControlStatusOutput;
};

export type DeleteApiV1RemotecontrolRegistrationResponse = DeleteApiV1RemotecontrolRegistrationResponses[keyof DeleteApiV1RemotecontrolRegistrationResponses];

export type DeleteApiV1RemotecontrolRegisterData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/remotecontrol/register';
};

export type DeleteApiV1RemotecontrolRegisterResponses = {
    /**
     * OK
     */
    200: RemoteControlStatusOutput;
};

export type DeleteApiV1RemotecontrolRegisterResponse = DeleteApiV1RemotecontrolRegisterResponses[keyof DeleteApiV1RemotecontrolRegisterResponses];

export type PostApiV1RemotecontrolRegisterData = {
    body: StartRegistrationInput;
    path?: never;
    query?: never;
    url: '/api/v1/remotecontrol/register';
};

export type PostApiV1RemotecontrolRegisterResponses = {
    /**
     * OK
     */
    200: RemoteControlStatusOutput;
};

export type PostApiV1RemotecontrolRegisterResponse = PostApiV1RemotecontrolRegisterResponses[keyof PostApiV1RemotecontrolRegisterResponses];

export type PostApiV1RemotecontrolRegisterWaitData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/remotecontrol/register/wait';
};

export type PostApiV1RemotecontrolRegisterWaitResponses = {
    /**
     * OK
     */
    200: RemoteControlStatusOutput;
};

export type PostApiV1RemotecontrolRegisterWaitResponse = PostApiV1RemotecontrolRegisterWaitResponses[keyof PostApiV1RemotecontrolRegisterWaitResponses];

export type PostApiV2DestinationListData = {
    body: DestinationListRequestDto;
    path?: never;
    query?: never;
    url: '/api/v2/destination/list';
};

export type PostApiV2DestinationListResponses = {
    /**
     * OK
     */
    200: DestinationListResponseDto;
};

export type PostApiV2DestinationListResponse = PostApiV2DestinationListResponses[keyof PostApiV2DestinationListResponses];

export type PostApiV2SystemTempDiskSpaceData = {
    body: TempDiskSpaceRequestDto;
    path?: never;
    query?: never;
    url: '/api/v2/system/temp-disk-space';
};

export type PostApiV2SystemTempDiskSpaceResponses = {
    /**
     * OK
     */
    200: TempDiskSpaceResponseDto;
};

export type PostApiV2SystemTempDiskSpaceResponse = PostApiV2SystemTempDiskSpaceResponses[keyof PostApiV2SystemTempDiskSpaceResponses];

export type PostApiV2FilesystemTestFilterData = {
    body: TestFilterRequestDto;
    path?: never;
    query?: never;
    url: '/api/v2/filesystem/test-filter';
};

export type PostApiV2FilesystemTestFilterResponses = {
    /**
     * OK
     */
    200: TestFilterResponseDto;
};

export type PostApiV2FilesystemTestFilterResponse = PostApiV2FilesystemTestFilterResponses[keyof PostApiV2FilesystemTestFilterResponses];

export type PostApiV2BackupListBrokenFilesData = {
    body: ListBrokenFilesRequestDto;
    path?: never;
    query?: never;
    url: '/api/v2/backup/list-broken-files';
};

export type PostApiV2BackupListBrokenFilesResponses = {
    /**
     * OK
     */
    200: ListBrokenFilesResponseDto;
};

export type PostApiV2BackupListBrokenFilesResponse = PostApiV2BackupListBrokenFilesResponses[keyof PostApiV2BackupListBrokenFilesResponses];

export type PostApiV2BackupPurgeBrokenFilesData = {
    body: PurgeBrokenFilesRequestDto;
    path?: never;
    query?: never;
    url: '/api/v2/backup/purge-broken-files';
};

export type PostApiV2BackupPurgeBrokenFilesResponses = {
    /**
     * OK
     */
    200: TaskStartedDto;
};

export type PostApiV2BackupPurgeBrokenFilesResponse = PostApiV2BackupPurgeBrokenFilesResponses[keyof PostApiV2BackupPurgeBrokenFilesResponses];

export type PostApiV2BackupDeleteVersionsData = {
    body: DeleteVersionsRequestDto;
    path?: never;
    query?: never;
    url: '/api/v2/backup/delete-versions';
};

export type PostApiV2BackupDeleteVersionsResponses = {
    /**
     * OK
     */
    200: TaskStartedDto;
};

export type PostApiV2BackupDeleteVersionsResponse = PostApiV2BackupDeleteVersionsResponses[keyof PostApiV2BackupDeleteVersionsResponses];

export type PostApiV2BackupListFilesetsData = {
    body: ListFilesetsRequestDto;
    path?: never;
    query?: never;
    url: '/api/v2/backup/list-filesets';
};

export type PostApiV2BackupListFilesetsResponses = {
    /**
     * OK
     */
    200: ListFilesetsResponseDto;
};

export type PostApiV2BackupListFilesetsResponse = PostApiV2BackupListFilesetsResponses[keyof PostApiV2BackupListFilesetsResponses];

export type PostApiV2BackupListFolderData = {
    body: ListFolderContentRequestDto;
    path?: never;
    query?: never;
    url: '/api/v2/backup/list-folder';
};

export type PostApiV2BackupListFolderResponses = {
    /**
     * OK
     */
    200: ListFolderContentResponseDto;
};

export type PostApiV2BackupListFolderResponse = PostApiV2BackupListFolderResponses[keyof PostApiV2BackupListFolderResponses];

export type PostApiV2BackupListVersionsData = {
    body: ListFileVersionsRequestDto;
    path?: never;
    query?: never;
    url: '/api/v2/backup/list-versions';
};

export type PostApiV2BackupListVersionsResponses = {
    /**
     * OK
     */
    200: ListFileVersionsOutputDto;
};

export type PostApiV2BackupListVersionsResponse = PostApiV2BackupListVersionsResponses[keyof PostApiV2BackupListVersionsResponses];

export type PostApiV2BackupSearchData = {
    body: SearchEntriesRequestDto;
    path?: never;
    query?: never;
    url: '/api/v2/backup/search';
};

export type PostApiV2BackupSearchResponses = {
    /**
     * OK
     */
    200: SearchEntriesResponseDto;
};

export type PostApiV2BackupSearchResponse = PostApiV2BackupSearchResponses[keyof PostApiV2BackupSearchResponses];

export type PostApiV2BackupSetVersionLabelData = {
    body: SetVersionLabelRequestDto;
    path?: never;
    query?: never;
    url: '/api/v2/backup/set-version-label';
};

export type PostApiV2BackupSetVersionLabelResponses = {
    /**
     * OK
     */
    200: SetVersionLabelResponseDto;
};

export type PostApiV2BackupSetVersionLabelResponse = PostApiV2BackupSetVersionLabelResponses[keyof PostApiV2BackupSetVersionLabelResponses];

export type PostApiV2DestinationTestData = {
    body: DestinationTestRequestDto;
    path?: never;
    query?: never;
    url: '/api/v2/destination/test';
};

export type PostApiV2DestinationTestResponses = {
    /**
     * OK
     */
    200: DestinationTestResponseDto;
};

export type PostApiV2DestinationTestResponse = PostApiV2DestinationTestResponses[keyof PostApiV2DestinationTestResponses];

export type GetApiV1WebmodulesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/webmodules';
};

export type GetApiV1WebmodulesResponses = {
    /**
     * OK
     */
    200: Array<IWebModule>;
};

export type GetApiV1WebmodulesResponse = GetApiV1WebmodulesResponses[keyof GetApiV1WebmodulesResponses];
