import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import {
  SparkleButtonComponent,
  SparkleDialogService,
  SparkleDividerComponent,
  SparkleIconComponent,
  SparkleListComponent,
  SparkleSidenavComponent,
} from '@sparkle-ui/core';
import LogoComponent from '../core/components/logo/logo.component';
import ServiceHubComponent from '../core/components/service-hub/service-hub.component';
import { DuplicatiServerService } from '../core/openapi';
import { AppAuthState } from '../core/states/app-auth.state';
import { BackupsState } from '../core/states/backups.state';
import { RelayconfigState } from '../core/states/relayconfig.state';
import { NotificationsState } from '../notifications/notifications.state';
import { ChangePassphraseAlertDialogComponent } from './change-passphrase-alert-dialog/change-passphrase-alert-dialog.component';
import { LayoutState } from './layout.state';

@Component({
  selector: 'app-layout',
  imports: [
    RouterOutlet,
    RouterLink,
    RouterLinkActive,
    SparkleSidenavComponent,
    SparkleIconComponent,
    SparkleListComponent,
    SparkleButtonComponent,
    SparkleDividerComponent,
    ServiceHubComponent,
    LogoComponent,
  ],
  templateUrl: './layout.component.html',
  styleUrl: './layout.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export default class LayoutComponent {
  #layoutState = inject(LayoutState);
  #dupServer = inject(DuplicatiServerService);
  #backupsState = inject(BackupsState);
  #relayConfigState = inject(RelayconfigState);
  #dialog = inject(SparkleDialogService);
  #notificaitonsState = inject(NotificationsState);
  #auth = inject(AppAuthState);

  relayIsEnabled = this.#relayConfigState.relayIsEnabled;
  isDarkMode = this.#layoutState.isDarkMode;

  ngOnInit() {
    this.#notificaitonsState.init();
    this.#backupsState.getBackups();
    return this.#dupServer.getApiV1Serversettings().subscribe({
      next: (res) => {
        const autogeneratedPassphrase = res['autogenerated-passphrase'] === 'True';
        const hasAskedForPasswordChange = res['has-asked-for-password-change'] === 'True';

        if (autogeneratedPassphrase && !hasAskedForPasswordChange) {
          this.#dialog.open(ChangePassphraseAlertDialogComponent, {
            maxWidth: '500px',
          });
        }
      },
    });
  }

  toggleBodyClass() {
    this.#layoutState.toggleBodyClass();
  }

  changeDefaultClientTo(client: 'ngclient' | 'ngax') {
    this.#setClientDefault(client);
    window.location.replace(`/${client}`);
  }

  logout() {
    this.#auth.logout();
  }

  #setClientDefault(client: 'ngclient' | 'ngax') {
    var d = new Date();
    d.setTime(d.getTime() + 90 * 24 * 60 * 60 * 1000);

    document.cookie = 'default-client=' + client + '; expires=' + d.toUTCString() + '; path=/';
  }
}
